version: '3.7'

services:
  my-app:
    image: node:18-alpine
    container_name: support-call-audio
    working_dir: /app
    volumes:
      - ./:/app
    command: node index.js
    ports:
      - "3333:3333"

